jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: last_success_build
      name: Find last successful build (current branch)
      uses: SamhammerAG/last-successful-build-action@v4
      with:
        branch: ${{ github.ref_name }}
        token: ${{github.token}}
        verify: true
        workflow: ${{github.workflow}}
    - continue-on-error: true
      id: last_success_build_any
      name: Find last successful build (any branch)
      uses: SamhammerAG/last-successful-build-action@v4
      with:
        token: ${{github.token}}
        verify: true
        workflow: ${{github.workflow}}
    - continue-on-error: true
      id: gradle_props
      uses: madhead/read-java-properties@latest
      with:
        all: true
        file: gradle.properties
    - continue-on-error: true
      name: Cache NG outputs
      uses: actions/cache@v4
      with:
        key: ${{ steps.gradle_props.outputs.minecraft_version }}-${{ steps.gradle_props.outputs.forge_version
          }}
        path: 'build/neoForge

          build/neoForm

          ~/.gradle

          .gradle

          '
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      env:
        BUILD_NUMBER: ${{ github.run_number }}
        GIT_COMMIT: ${{ github.sha }}
        GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ steps.last_success_build.outputs.sha !=
          github.sha && steps.last_success_build.outputs.sha || steps.last_success_build_any.outputs.sha
          }}
      name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: build outputChangelog
        cache-read-only: false
        gradle-version: wrapper
    - continue-on-error: true
      name: Upload to workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        path: 'build/libs/

          build/changelog.html

          '
    - continue-on-error: true
      id: gh_release
      name: GH Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: build/changelog.md
        files: build/libs/!(MekanismDefense*).jar
        tag_name: v${{ steps.gradle_props.outputs.minecraft_version }}-${{ steps.gradle_props.outputs.mod_version
          }}.${{ github.run_number }}
        target_commitish: ${{ github.sha }}
    - continue-on-error: true
      env:
        BUILD_NUMBER: ${{ github.run_number }}
        CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
        GIT_COMMIT: ${{ github.sha }}
        GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ steps.last_success_build.outputs.sha !=
          github.sha && steps.last_success_build.outputs.sha || steps.last_success_build_any.outputs.sha
          }}
        MEK_MAVEN_PW: ${{ secrets.MEK_MAVEN_PW }}
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      name: Publish
      uses: gradle/gradle-build-action@v3
      with:
        arguments: curseforge modrinth publish
        cache-read-only: false
        gradle-version: wrapper
    - continue-on-error: true
      id: read_changelog
      name: Read changelog
      uses: andstor/file-reader-action@v1
      with:
        path: build/changelog.md
    - continue-on-error: true
      name: Announce Release
      uses: tsickert/discord-webhook@v6.0.0
      with:
        embed-description: 'Available on Curseforge after approval.


          ${{ steps.read_changelog.outputs.contents }}

          '
        embed-title: Mekanism ${{ steps.gradle_props.outputs.mod_version }}.${{ github.run_number
          }} for Minecraft ${{ steps.gradle_props.outputs.minecraft_version }} Released
        embed-url: ${{ steps.gh_release.outputs.url }}
        webhook-url: ${{ secrets.WEBHOOK_URL }}
name: Build & Publish
on:
  repository_dispatch:
    types: trigger-ga___gradle-publish.yml
